### ISSUE TITLE
Key revocation page does not display status.

### ISSUE THREAD

**Issue by thompsonm-ANL** [Argonne-National-Laboratory/meg-server#2]
Currently it just displays a blank page.  We should let the user know what has happened, if their key has been revoked, and what this means.

**Comment by bbusenius** [comment]
I opened a similar issue [for the android app](https://github.com/Argonne-National-Laboratory/MEGAndroid/issues/7). Since the interaction involves both the server and the app, should we track the issue in both places or is one of the two preferable? I guess, there will be needed work on both pieces. We'll at least want to track the relation.

**Comment by JoshuaLyle** [comment]
A revocation message is returned after the user revokes from their email client
